version: 2
jobs:
  frontend_format:
    docker:
      - image: node:10.13.0
    steps:
      - checkout
      - run:
          command: |
            yarn install --no-optional
            yarn run format:check
workflows:
  version: 2
  build-test:
    jobs:
      - frontend_format