version: 2
jobs:
  frontend_format:
    docker:
      - image: node:10.8.0
    steps:
      - checkout
      - run:
          command: |
            yarn install --no-optional
            yarn run format:check
  frontend_test:
    docker:
      - image: node:10.8.0
    steps:
      - checkout
      - run:
          command: |
            yarn install --no-optional
            yarn run test
workflows:
  version: 2
  build-test:
    jobs:
      - frontend_test
      - frontend_format